### ISSUE TITLE
Authentication Functionality

### ISSUE THREAD

**Issue by jungj5** [parkt2/kadopon-village#1]
Pretty standard. Setup authentication functionality for Kadopon, allowing users to sign up with emails and login upon account creation. 
## Required
* UI to login from
* Backend to handle interactions between UI and database.
* MongoDB will be used to store these accounts. 

## Technologies
* MongoDB/Mongoose
* Node/React/Redux
* HTML/CSS

**Comment by chocolatemelt** [comment]
leaving this for later, not part of mvp
